server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.0.0.243:3306/test?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.0.0.243:3306/test?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456